name: Optimize SVGs

on:
  schedule:
    - cron: "0 0 * * 1"
  workflow_dispatch:

permissions:
  pull-requests: write
  contents: write

jobs:
  optimize-svgs:
    runs-on: ubuntu-latest
    if: github.repository == 'Hamster45105/lawnicons'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      
      - name: Install SVGO
        run: npm install -g svgo svg-pathdata
      
      - name: Optimize SVGs
        id: svgo
        run: svgo --config=svgo.config.cjs --folder=svgs --recursive
           
      - name: Create Pull Request
        id: create-pr
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Optimize ${{steps.svgo.outputs.OPTIMIZED_COUNT}} SVG(s)
          title: 'Optimize ${{steps.svgo.outputs.OPTIMIZED_COUNT}} SVG(s)'
          branch: optimize-svgs
          delete-branch: true
      
      - name: Enable Pull Request Automerge
        if: steps.create-pr.outputs.pull-request-operation != 'none' || steps.create-pr.outputs.pull-request-operation != 'closed'
        run: gh pr merge --merge --auto ${{ steps.create-pr.outputs.pull-request-number }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
